id: simulation
name: Simulation
type: simulation

battery_cutoff: 18.0  # 5 x 3.6V, e-stop, should return to dock before that
max_speed: 0.3 # 0.44  # m/s
min_speed: 0  # m/s
max_omega: 0.5  # rad/s
wheel_base: 0.325  # wrong, not needed

mower:
  cut_power: 0.3
  cut_diameter: 0.2

dock:
  position:
    x: 0
    y: -3
  heading: 0
