exterior:
  - x: -3.2  # hekkehjørne
    y: -1

  # hekkeknekk roser mot garasje
  - x: 2.0
    y: -1
  - x: 2.7
    y: -0.4

  # trapp
  - x: 5.5
    y: -0.4
  - x: 5.5
    y: -0.3

 # sville hjørne
  - x: 14.7
    y: 0
  - x: 15.8
    y: 0.5

  - x: 17.8
    y: 3.0

  - x: 19
    y: 3.0

  - x: 19.2
    y: 0

  - x: 16.7 # heilt i hjørnet, robot på skrå
    y: -3.5

  - x: 13.7 # lita bjørk v/dokkestua
    y: -4.8

  - x: 11 # venstre hjørne ved steinvegg
    y: -6.8

  - x: 8.6 # trapp
    y: -7.0

  - x: 5.7 # rør
    y: -6.7

  # sandkasse
  - x: 4.1 # sandkasse TL
    y: -6.7
  - x: 4.1 # sandkasse BL
    y: -4.9 # crash on fenceshrink with -5.2
  - x: 2.0 # sandkasse BR
    y: -4.9
  - x: 2.0 # sandkasse MR
    y: -6.5

  # gran til N/NW: 0 -5.7
  - x: 1.3
    y: -6.5
  - x: 1.3
    y: -6.2
  - x: 0.9
    y: -5.8
  - x: 0.4
    y: -5.8
  - x: 0
    y: -6.2
  - x: 0
    y: -6.6
  - x: 0.4
    y: -7
  - x: 0.9
    y: -7
  - x: 1.3
    y: -6.6

  # bak gran til sandkasse og steingrøft
  - x: 2.0
    y: -6.6
  - x: 2.0
    y: -8.5
  - x: 0
    y: -9

  # bak til ny gran
  - x: -3
    y: -9.6

  - x: -3 # fram forbi ny gran
    y: -7.7

  - x: -5.5 # ny gran
    y: -7.7

  # bak til kompost
  - x: -5.5
    y: -10.2
  - x: -8.5
    y: -10.5
  - x: -8.5
    y: -9.5

  - x: -10.8 # til rododendron
    y: -9.5

  - x: -11.3 # under midten av slacklina
    y: -7.5

  - x: -11.9 # rosa
    y: -4

  # epletre - 0.5m nærmere midten enn rosa, på y=0
  - x: -12.2
    y: -1.1
  - x: -11.8
    y: -0.8
  - x: -11.8
    y: -0.2
  - x: -12.1
    y: 0.1

  # rabarbrahjørne
  - x: -12
    y: 4

  - x: -11.3 # hjørne mellom rips og trapp
    y: 4

  - x: -10.8 # trapp mot rabarbra
    y: 5

  - x: -10.0 # trapp mot drue
    y: 5


#  - x: -10.0 # solbær veranda
#    y: 2.5

#  - x: -10.0 # solbær veranda
#    y: 2.5

  - x: -10.0 # solbær veranda
    y: 1.9

  - x: -9.8 # solbær veranda (-9.6)
    y: 1.3

  - x: -9.8 # hjørne hekk
    y: -0.1

  - x: -3.6 # knekk hekk
    y: -0.4

reference:
  latitude: 59.81665870
  longitude: 10.36129810
  rotation: -20


dock:
  position:
    x: 3
    y: -1
  heading: 0
  distance: 0.4
  distance2: 0.8
